# Generated by Django 5.1 on 2024-09-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('agreementId', models.AutoField(primary_key=True, serialize=False)),
                ('referenceNr', models.IntegerField()),
                ('startDate', models.DateField()),
                ('months', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('info', models.TextField()),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('modelId', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('keys', models.IntegerField()),
                ('low', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('bRows', models.IntegerField()),
                ('fb', models.IntegerField()),
                ('reedsR', models.IntegerField()),
                ('reedsL', models.IntegerField()),
                ('reeds_fb', models.IntegerField()),
                ('range_fb', models.IntegerField()),
                ('fb_low', models.IntegerField()),
                ('regR', models.IntegerField()),
                ('regL', models.IntegerField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
                ('keyboard', models.FloatField()),
                ('newPrice', models.FloatField()),
                ('usedPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('rateId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('municipality', models.CharField(max_length=128)),
                ('settlement', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('house', models.CharField(max_length=128)),
                ('apartment', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institution', models.CharField(blank=True, max_length=128, null=True)),
                ('teacher', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('agreementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.agreements')),
            ],
        ),
        migrations.CreateModel(
            name='Rendipillid',
            fields=[
                ('instrumentId', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=128)),
                ('serial', models.CharField(max_length=128)),
                ('info_est', models.TextField()),
                ('info_eng', models.TextField()),
                ('status', models.CharField(max_length=128)),
                ('price_level', models.IntegerField(default=1)),
                ('modelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.model')),
            ],
        ),
        migrations.AddField(
            model_name='agreements',
            name='instrumentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rendipillid'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
    ]
