# Generated by Django 5.1 on 2024-09-09 07:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('agreementId', models.AutoField(primary_key=True, serialize=False)),
                ('referenceNr', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('startDate', models.DateField()),
                ('months', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('ContactSigned', 'Contact Signed'), ('EndingSoon', 'Ending Soon'), ('Ended', 'Ended'), ('Finished', 'Finished')], default='Created', editable=False, max_length=15)),
                ('invoice_interval', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'agreements',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('modelId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('keys', models.IntegerField()),
                ('low', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('bRows', models.IntegerField()),
                ('fb', models.IntegerField(default=0)),
                ('reedsR', models.IntegerField()),
                ('reedsL', models.IntegerField()),
                ('reeds_fb', models.IntegerField(default=0)),
                ('range_fb', models.IntegerField(default=0)),
                ('fb_low', models.IntegerField(default=0)),
                ('regR', models.IntegerField()),
                ('regL', models.IntegerField()),
                ('height', models.FloatField(default=36)),
                ('width', models.FloatField(default=18)),
                ('length', models.FloatField(default=36)),
                ('weight', models.FloatField()),
                ('keyboard', models.FloatField()),
                ('folds', models.IntegerField(blank=True, null=True)),
                ('deep', models.IntegerField(blank=True, null=True)),
                ('bass_start_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('newPrice', models.FloatField(default=2000)),
                ('usedPrice', models.FloatField(default=1000)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
            ],
            options={
                'db_table': 'rates',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('country', models.CharField(default='Estonia', max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('municipality', models.CharField(max_length=64)),
                ('settlement', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('house', models.CharField(max_length=64)),
                ('apartment', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(default='+372', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('institution', models.CharField(blank=True, max_length=64, null=True)),
                ('teacher', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(choices=[('Eesti', 'Eesti'), ('English', 'English')], default='Eesti', max_length=7)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Issued', 'Issued'), ('Sent', 'Sent'), ('Paid', 'Paid')], default='Issued')),
                ('agreementId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.agreements')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Rendipillid',
            fields=[
                ('instrumentId', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=64)),
                ('info_est', models.TextField()),
                ('info_eng', models.TextField()),
                ('status', models.CharField(default='Available', max_length=64)),
                ('modelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.model')),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rates')),
            ],
            options={
                'db_table': 'rendipillid',
            },
        ),
        migrations.AddField(
            model_name='agreements',
            name='instrumentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rendipillid'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
    ]
