# Generated by Django 5.1 on 2024-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='agreementId',
            new_name='agreement',
        ),
        migrations.AddField(
            model_name='invoices',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Sent', 'Sent'), ('Paid', 'Paid')], default='Issued', max_length=10),
        ),
    ]
