# Generated by Django 5.1 on 2024-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_change_users_language_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('ContactSigned', 'Contact Signed'), ('EndingSoon', 'Ending Soon'), ('Ended', 'Ended'), ('Finished', 'Finished')], default='Created', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(choices=[('EST', 'Eesti'), ('ENG', 'English')], default='EST', max_length=3),
        ),
    ]
