# Generated by Django 5.1 on 2024-09-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='modelId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendipillid',
            name='modelId',
            field=models.ForeignKey(db_column='modelId', on_delete=django.db.models.deletion.CASCADE, to='myapp.model'),
        ),
        migrations.AlterModelTable(
            name='model',
            table='model',
        ),
        migrations.AlterModelTable(
            name='rendipillid',
            table='rendipillid',
        ),
    ]
