# Generated by Django 5.1 on 2024-09-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_model_modelid_alter_rendipillid_modelid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='rendipillid',
            name='modelId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.model'),
        ),
    ]
