# Generated by Django 5.1 on 2024-09-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_model_options_alter_rendipillid_modelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendipillid',
            name='color',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rendipillid',
            name='serial',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rendipillid',
            name='status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(default='Estonia', max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='+372', max_length=128),
        ),
    ]
