# Generated by Django 5.1.1 on 2024-11-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_payment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
